### ISSUE TITLE
[New sniff] No disabling of the admin toolbar.

### ISSUE THREAD

**Issue by jrfnl** [WPTRT/WordPress-Coding-Standards#1]
#### Rule:

No hiding of the admin bar - check if `show_admin_bar( false )` is called or if `add_filter( 'show_admin_bar', '__return_false' )` is somewhere in the code. 

Ref: https://make.wordpress.org/themes/handbook/review/required/#core-functionality-and-features
#### Theme check file covering this rule:

https://github.com/Otto42/theme-check/blob/master/checks/adminbar.php
#### To do:

~~\- [ ] Create unit tests~~
~~\- [ ] Create new sniff~~
- [ ] Open PR upstream in WPCS to improve the admin bar removal sniff.
- [ ] Add `WordPress_Sniffs_VIP_AdminBarRemovalSniff` sniff to the ruleset.

**Comment by jrfnl** [comment]
By the looks of it, there already is a sniff for this in WP-VIP: https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/blob/develop/WordPress/Sniffs/VIP/AdminBarRemovalSniff.php

The check in Theme Check however is more comprehensive, so I suggest improving the VIP check upstream and then adding it to the Theme rule set.

**Comment by grappler** [comment]
@jrfnl Was there something specific you saw that needed improving other then add a check for `#wpadmin` and `.show-admin-bar`?

**Comment by jrfnl** [comment]
@grappler I believe those checks should be done on both the PHP as well as CSS files and should be quite specific. I mean, a theme changing the color of the admin bar to be in line with their front-end theme should **_not_** see this notice.

I also think that for the existing PHP function based check, the parameter values should be checked against some whitelisted values.
I don't think: `add_filter( 'show_admin_bar', '__return_true' );` should trigger this error and while it will be very rare indeed to come across that code, it shouldn't be hard to check for.

I also think the sniff should be moved from `Sniffs/VIP/` to `Sniffs/WP/` as it's not VIP specific, though we will need to check if VIP agrees with the proposed adjustments and if not, have a second sniff just for the CSS related checks.

I have made a small start locally for the changes needed upstream - mainly creating the unit tests. Want me to share this for you to continue ?

**Comment by justintadlock** [comment]
> I believe those checks should be done on both the PHP as well as CSS files and should be quite specific. I mean, a theme changing the color of the admin bar to be in line with their front-end theme should not see this notice.

Definitely agree.  I've said as much and thought that we had decided not to target CSS a while back.  I think we'd all be OK with a check for something like this (or variations):

	#wpadminbar { display: none; }

> I also think that for the existing PHP function based check, the parameter values should be checked against some whitelisted values.
> I don't think: `add_filter( 'show_admin_bar', '__return_true' );` should trigger this error and while it will be very rare indeed to come across that code, it shouldn't be hard to check for.

Force-showing is as equally bad as force hiding it.  Whether to show/hide the admin bar is outside the scope of themes.  This is core and plugin territory.

**Comment by jrfnl** [comment]
> Whether to show/hide the admin bar is outside the scope of themes. This is core and plugin territory.

The altered sniff will need to be as re-usable as possible as it *is* used for plugins as well in VIP context. So in that case, we either need a property switch which allows for checking that those functions are used at all (themes) or checking that those functions don't hide the admin bar (rest of the world).
