### ISSUE TITLE
[Implement sniff] Everything in the global namespace should be prefixed

### ISSUE THREAD

**Issue by jrfnl** [WPTRT/WordPress-Coding-Standards#129]
#### Rule type:
Error

#### Rule:

I'm not sure whether anything about this is currently in the handbook, but it is best practice to prefix all function/class/constant/variable/hook names used in the global namespace to prevent naming collisions with plugins and potentially the parent-theme.

####  Decision needed:
Check whether this is currently covered the handbook and if it isn't, a decision is needed on whether it should be added.

**_Advice_**: Add to the handbook.

##### Notes for implementation:
* There is an existing sniff - `WordPress.NamingConventions.PrefixAllGlobals` - for this in WPCS upstream which will be in WPCS 0.12.0. The sniff *does* require a set of prefixes to be passed otherwise it will not have anything to check against.
See: https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/pull/907

#### To do:
- [x] Add the rule in the Theme Review handbook to the **_Requirements_** page.
- [ ] Add existing `WordPress.NamingConventions.PrefixAllGlobals` sniff to the ruleset after the current version of WPCS has been merged back into TRTCS.

**Comment by carolinan** [comment]
The requirement reads 
"Provide a unique prefix for everything the Theme defines in the public namespace, including options, functions, global variables, constants, post meta, etc."

**Comment by jrfnl** [comment]
@carolinan Excellent! Thanks. In that case, only the sniff needs to be added to the ruleset.

**Comment by justintadlock** [comment]
Just want to note that I'm a bit iffy on meta necessarily being prefixed.  In general, I usually say that it must be.  However, there are some common keys that theme authors use from theme to theme.  Using a common key gives you a bit more portability in an area where WP sucks at portability.

Prefixing should be done here if it's something specific to this one particular theme.

For example, suppose we allowed themes to register post types, I wouldn't want them prefixing their "testimonial" post type as `themename_testimonial`.  I'd want them sticking with a more standard `testimonial`.

I'd treat metadata the same.  If it's specific to the theme, prefix.  If it's something that other themes could use, stick with a un-prefixed, common naming system.

**Comment by jrfnl** [comment]
@justintadlock The sniff (currently) does not check meta keys or post types. It only checks PHP globals (variables, functions, classes, constants) and hook names for WP.
