### ISSUE TITLE
Can we check for core CSS classes being defined?

### ISSUE THREAD

**Issue by joyously** [WPTRT/WordPress-Coding-Standards#135]
There is not an explicit Review Guideline for this, but all themes need to style the core defined CSS classes. A lot of themes either leave them out or put empty rules for them.

This [codex page](https://codex.wordpress.org/CSS) mentions the core classes
`wp-caption, alignright, alignleft, aligncenter, alignnone, screen-reader-text`
but does not mention `sticky, gallery-caption, bypostauthor`, which are considered optional (?).

**Comment by grappler** [comment]
Here are a list of classes that the previous theme check checked for https://github.com/WordPress/theme-check/blob/master/checks/style_needed.php

**Comment by joyously** [comment]
That's good, but I think it's why I was seeing them defined empty.

**Comment by jrfnl** [comment]
Closing as this can't be reliably checked by PHPCS.
