### ISSUE TITLE
After running the plugin, it shows up warnings and a notice

### ISSUE THREAD

**Issue by bilal-pp** [WPTRT/WordPress-Coding-Standards#143]
Hi,

After selecting the theme name from the drop-down and clicking on the go button, I get the the following

<br />
<b>Notice</b>:  tempnam(): file created in the system's temporary directory in <b>/Applications/XAMPP/xamppfiles/htdocs/breeze-theme/wp-content/plugins/theme-sniffer/vendor/squizlabs/php_codesniffer/CodeSniffer/Reporting.php</b> on line <b>177</b><br />
<br />
<b>Warning</b>:  fopen(): Filename cannot be empty in <b>/Applications/XAMPP/xamppfiles/htdocs/breeze-theme/wp-content/plugins/theme-sniffer/vendor/squizlabs/php_codesniffer/CodeSniffer/Reporting.php</b> on line <b>177</b><br />
<br />
<b>Warning</b>:  fwrite() expects parameter 1 to be resource, boolean given in <b>/Applications/XAMPP/xamppfiles/htdocs/breeze-theme/wp-content/plugins/theme-sniffer/vendor/squizlabs/php_codesniffer/CodeSniffer/Reporting.php</b> on line <b>183</b><br />
<br />
<b>Warning</b>:  stream_get_meta_data() expects parameter 1 to be resource, boolean given in <b>/Applications/XAMPP/xamppfiles/htdocs/breeze-theme/wp-content/plugins/theme-sniffer/vendor/squizlabs/php_codesniffer/CodeSniffer/Reporting.php</b> on line <b>242</b><br />
<br />
<b>Warning</b>:  file_get_contents(): Filename cannot be empty in <b>/Applications/XAMPP/xamppfiles/htdocs/breeze-theme/wp-content/plugins/theme-sniffer/vendor/squizlabs/php_codesniffer/CodeSniffer/Reporting.php</b> on line <b>244</b><br />
<br />
<b>Warning</b>:  fclose() expects parameter 1 to be resource, boolean given in <b>/Applications/XAMPP/xamppfiles/htdocs/breeze-theme/wp-content/plugins/theme-sniffer/vendor/squizlabs/php_codesniffer/CodeSniffer/Reporting.php</b> on line <b>245</b><br />
Time: 25399106 mins, 9.16 secs; Memory: 16Mb

Also I am attaching the screenshot of the selected standards and options. Please note I am running the plugin on my localhost (XAMPP).

Thanks,
Bilal Ahmed
![screen shot 2018-04-17 at 12 04 33 pm](https://user-images.githubusercontent.com/20988725/38852455-9396886c-4237-11e8-810a-ac07b08a92c0.png)

**Comment by carolinan** [comment]
Hi
This is not the repository for the plugin. Go here instead: https://github.com/WPTRT/theme-sniffer

Make sure that you download the correct version of the plugin that is linked in the readme.
