### ISSUE TITLE
PHP 7.2 Deprecated 

### ISSUE THREAD

**Issue by benlumia007** [WPTRT/WordPress-Coding-Standards#144]
Apparently VVV upgraded their PHP to 7.2 and getting the following deprecated

<b>Deprecated</b>:  Function create_function() is deprecated in <b>/srv/www/getbenonit/public_html/wp-content/plugins/theme-sniffer/vendor/wp-coding-standards/wpcs/WordPress/Sniffs/VIP/ValidatedSanitizedInputSniff.php</b> on line <b>93</b><br />

I was told to open an issue here regarding the deprecated. 

as @dingo-d mention ed follow

This seems like an upstream issue with the WordPress Coding Standards (vendor/wp-coding-standards/wpcs/WordPress/Sniffs/VIP/ValidatedSanitizedInputSniff.php).

**Comment by dingo-d** [comment]
I'll review the composer file in the next release of the theme sniffer, this should sort this issue out I think. 👍

**Comment by jrfnl** [comment]
@dingo-d Actually, that won't necessarily work as the code for the sniffs in this repo need to be updated to be compatible with PHPCS 3.0 (which they currently aren't).

Basically, this repo needs to be properly updated. It would also be a good idea to work through some of the open PRs here.

**Comment by dingo-d** [comment]
I totally forgot that this is a fork of the WPCS. You're right, this should be updated. I'll try to make some updates.

**Comment by jrfnl** [comment]
PR #145 should take care of this.
