### ISSUE TITLE
[Implement sniff ?] No alternative PHP open tags ?

### ISSUE THREAD

**Issue by jrfnl** [WPTRT/WordPress-Coding-Standards#15]
#### Decision needed by Theme Review Board:

There is currently no rule to check for alternative PHP open tags, like ASP tags and the PHP Script tag.

There has just been a [discussion upstream in WPCS](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/issues/580) that these should not be allowed in general and it is expected that the [associated sniff](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/pull/585) will be merged into WPCS.

Should alternative PHP open tags be forbidden in themes as well ?

**_Advice_**: Follow WPCS's lead in this.
#### To do:
- [x] If agreed this should be a rule - add `WordPress.PHP.DisallowAlternativeOpenTag` sniff to the ruleset.
- [ ] Add the rule in the Theme Review handbook to the Requirements page.

**Comment by grappler** [comment]
Green light to go ahead :
https://make.wordpress.org/themes/2016/07/12/meeting-notes-for-2016-july-12/
