### ISSUE TITLE
[Implement sniff ?] Prevent path disclosure on add_theme_page ?

### ISSUE THREAD

**Issue by jrfnl** [WPTRT/WordPress-Coding-Standards#18]
#### Decision needed by Theme Review Board:
There is currently no rule to check for the use of `__FILE__`  in combination with `add_theme_page()` which could lead to full path disclosure..

There is already a sniff available in WPCS which *will* check this - `WordPress.VIP.PluginMenuSlug`.

Should this sniff be activated for theme reviews ?

**_Advice_**: Follow WP VIP's lead in this.

#### To do:
- [ ] If agreed this should be a rule - add `WordPress.VIP.PluginMenuSlug` sniff to the ruleset.
- [ ] Add the rule in the Theme Review handbook to the Requirements page.

**Comment by emiluzelac** [comment]
This path should not be used period and in combination with anything theme
related.

I would agree for the rule only if we generalize it.

**Comment by grappler** [comment]
@emiluzelac We can cover not allowing `__FILE__` completly in another sniff. https://github.com/WPTRT/WordPress-Coding-Standards/issues/23 I would lean to allow this for now till the other sniff has been implimented.

**Comment by justintadlock** [comment]
I disagree to a generalized rule on `__FILE__`.  The above, *specific rule that addresses a specific issue* is what we need to go for.  When you make generalized checks, you throw out any legit use cases.

**Comment by emiluzelac** [comment]
What is a legit use for it?

**Comment by joyously** [comment]
I use a theme that uses __FILE__ for a template trace when in debug mode, so you can see which template files were used to create the final page. That's very helpful when writing a child theme.

**Comment by justintadlock** [comment]
> What is a legit use for it?

Drop-in libraries often need it for finding correct paths and so on. 

The real question though is why discourage the use in the first place?  Is there are particular issue?  If so, we should address those specifically.

**Comment by emiluzelac** [comment]
Consistency. Can drop-in libraries not use core paths?

**Comment by Pross** [comment]
> Consistency. Can drop-in libraries not use core paths?
Some drop-ins are used in plugins and themes.

**Comment by jrfnl** [comment]
> Is there are particular issue? If so, we should address those specifically.

And in this case there is a particular issue this would address, see the original issue description above.

**Comment by emiluzelac** [comment]
That makes sense @Pross, thanks :)

**Comment by grappler** [comment]
As the sniff prevents a security issue I am going to add the check.

**Comment by grappler** [comment]
PR #19 merged...
