### ISSUE TITLE
[Implement sniff] No PHP short tags

### ISSUE THREAD

**Issue by jrfnl** [WPTRT/WordPress-Coding-Standards#2]
#### Rule:

No short open tags allowed.

Ref: https://make.wordpress.org/themes/handbook/review/required/theme-check-plugin/#additional-checks
#### Theme check file covering this rule:

https://github.com/Otto42/theme-check/blob/master/checks/phpshort.php
#### Decision needed by Theme Review Board:

In the Theme Check plugin, this rule currently generates a warning and the rule is not mentioned on the Theme Review Requirements page.

The existing PHPCS sniff implementation for this - `Generic.PHP.DisallowShortOpenTag` - generates an error. If this should be a warning, either a PR needs to be submitted upstream to PHPCS to allow for changing the error level or alternatively the existing sniff would need to be extended/copied to a WP specific sniff which would do the same, but generate a warning instead of an error.

**_Advice_**: As short open tags have been removed in PHP 7, I would suggest making this rule a requirement and raising the error level to error instead of warning.
#### To do:
- [x] If agreed this should be an error - add existing `Generic.PHP.DisallowShortOpenTag` sniff to the ruleset.
- [x] Add the rule in the Theme Review handbook to the Requirements page.

**Comment by grappler** [comment]
Green light to go ahead :
https://make.wordpress.org/themes/2016/07/12/meeting-notes-for-2016-july-12/

**Comment by grappler** [comment]
I just ran the sniff `phpcs --standard=WordPress-Theme *` on a theme and it returned an error for `.MD` and `.jpg` files which does not make sense.

**Comment by jrfnl** [comment]
Interesting. As far as I know, by default, PHPCS runs on PHP, JS and CSS files. Nothing else.
Would need to look into what's going there.
