### ISSUE TITLE
[New sniff] Check for disallowed theme related WP constants

### ISSUE THREAD

**Issue by grappler** [WPTRT/WordPress-Coding-Standards#23]
#### Rule:
**ERROR** : Check for usage of deprecated WP constants **_relating to themes_** ~~and discouraged PHP constants e.g `__FILE__`~~. We could probably extend an existing sniff of similar ilk for this.

Ref: https://make.wordpress.org/themes/handbook/review/required/#core-functionality-and-features

#### Theme check file covering this rule:
https://github.com/Otto42/theme-check/pull/162/files 

#### Decision needed:
Confirmation is needed that the current list is correct. If not, input is needed about which other theme related WP constants should (not) be covered by this sniff.

#### To do:
- [x] Review the current list of constants being checked for and confirm that this covers the theme related WP constants. If not, please leave a comment in this issue thread with details of the changes needed.
- [x] Expand and clarify the rule in the Handbook.
- [x] Create unit tests
- [x] Create new sniff
- [ ] Open new item for related but distinct PHP constants sniff
- [ ] If needed: Open new item for related but distinct other constants sniff

**Comment by emiluzelac** [comment]
Here's my snippet:

Theme needs to properly load files, but also to be consistent as well. 

There are several functions available for getting the path: 

- get_template_directory - Filter the current theme directory path.

- get_template_directory_uri  - Filter the current theme directory URI. 

- get_stylesheet_directory - Filter the stylesheet directory path for current theme. 

- get_stylesheet_directory_uri - Filter the stylesheet directory URI. 

http://justintadlock.com/archives/2010/11/17/how-to-load-files-within-wordpress-themes

**Comment by jrfnl** [comment]
Is the current list as can be found in https://github.com/Otto42/theme-check/pull/162/files is still complete enough as a starting point ?

**Comment by jrfnl** [comment]
Also: looking at the PR - we may want to split this into two sniffs:
* one for path related constants
* one for theme support related constants

I think that would make it easier to maintain and extend.

**Comment by jrfnl** [comment]
Also looking at the rule in the handbook, I'd like to add an action item to expand and clarify the rule as it currently isn't explicit enough and doesn't cover all that is covered by the Theme Check PR IMHO:

> Use get_template_directory() rather than TEMPLATEPATH to return the template path.
> Use get_stylesheet_directory() rather than STYLESHEETPATH to return the stylesheet path.

**Comment by justintadlock** [comment]
I'd say no to "discouraged" (not sure decided this was discouraged) PHP constants like `__FILE__`. That can be quite useful.

**Comment by jrfnl** [comment]
@justintadlock I guess this was the inspiration: https://github.com/WPTRT/WordPress-Coding-Standards/issues/18

**Comment by grappler** [comment]
The reason to not support the constants is that they have been deprecated. I think the list is good and we can always extend it if necessary. I am looking to find a way we can best document these requirements.

**Comment by jrfnl** [comment]
> The reason to not support the constants is that they have been deprecated

In that case - let me adjust the PR and name the sniff DeprecatedWPConstants instead of Forbidden.

**Comment by grappler** [comment]
Documented here. https://make.wordpress.org/themes/handbook/review/required/requirements-dafts/
