### ISSUE TITLE
[New sniff] Check for <title>

### ISSUE THREAD

**Issue by carolinan** [WPTRT/WordPress-Coding-Standards#25]
#### Rule:

**ERROR** : The theme must not use the &lt;title&gt; tag.

Ref: https://make.wordpress.org/themes/handbook/review/required/
"You should support up to 2 versions behind the current WordPress version."

The test and the sniff should include this exception: inline SVG code.
#### Theme check file covering this rule:

https://github.com/Otto42/theme-check/blob/master/checks/title.php
#### To do:
- [x] Create unit tests
- [x] Create new sniff

**Comment by emiluzelac** [comment]
Yep, we should let WordPress manage the document title and via `add_theme_support( 'title-tag' );` instead. 

https://make.wordpress.org/core/2014/10/29/title-tags-in-4-1/

**Comment by carolinan** [comment]
I believe there will be a separate sniff for the _required_ add theme supports.

**Comment by grappler** [comment]
This has been merged
