### ISSUE TITLE
[Implement sniff] Verify that the i18n functions are used properly

### ISSUE THREAD

**Issue by jrfnl** [WPTRT/WordPress-Coding-Standards#31]
#### Rule type:

Error
#### Rule:

From what I can see, there are actually 5 distinct i18n related rules which may need sniffs - this issue covers the **fifth item** on the list.
1. All theme text strings are to be translatable. (#33)
2. Include a text domain in style.css (#34)
3. Use a single unique theme slug – as the theme slug appears in style.css. If it uses a framework then no more than 2 unique slugs. (#35)
4. Can use any language for text, but only use the same one for all text. (#33)
5. **Correct usage of the WP i18n functions.**

Refs:
https://make.wordpress.org/themes/handbook/review/required/#language
https://make.wordpress.org/themes/handbook/review/required/theme-check-plugin/#additional-checks

There is an existing sniff within WPCS which has extensive coverage in checking whether the i18n functions are used correctly.
#### Theme check file covering this rule:

https://github.com/Otto42/theme-check/blob/master/checks/i18n.php
https://github.com/Otto42/theme-check/blob/master/checks/textdomain.php
#### To do:
- [x] Add existing `WordPress.WP.I18n` sniff to the ruleset.
- [ ] Maybe add some more information to the handbook about what the correct usage is of the i18n functions ?

**Comment by grappler** [comment]
The theme review handbook should only contain the requirements. The documentation for i18n for themes can be found in the theme development handbook https://developer.wordpress.org/themes/functionality/internationalization/

**Comment by grappler** [comment]
Closing as the PR is merged
