### ISSUE TITLE
[Implement sniff] Validate and/or sanitize all input, escape all output

### ISSUE THREAD

**Issue by jrfnl** [WPTRT/WordPress-Coding-Standards#37]
#### Rule type:
Error

#### Rule:

> Validate and/or sanitize untrusted data before entering into the database. All untrusted data should be escaped before output.

Ref: https://make.wordpress.org/themes/handbook/review/required/#code

#### Theme check file covering this rule:
N/A

#### To do:
- [ ] Add existing `WordPress.XSS.EscapeOutput` sniff to the ruleset.
- [ ] Add existing `WordPress.VIP.ValidatedSanitizedInput` sniff to the ruleset.

**Comment by khacoder** [comment]
These sniffs are generating many false positives, unless I am missing something.

**Comment by jrfnl** [comment]
@khacoder Could you give some examples of the false positives you've seen ? Or maybe even open an issue with the examples upstream ?
Based on good examples which could be added to the unit tests, the sniff could possibly be further fine-tuned.
