### ISSUE TITLE
[Implement sniff] Enqueue all scripts and styles

### ISSUE THREAD

**Issue by fklein-lu** [WPTRT/WordPress-Coding-Standards#39]
**Rule type:**
Error 

**Rule:**

> No hard coding of scripts and styles unless a browser workaround script. Everything should be enqueued.

Ref: https://make.wordpress.org/themes/handbook/review/required/#stylesheets-and-scripts

**Existing Sniff:**

https://github.com/WPTRT/WordPress-Coding-Standards/blob/feature/theme-review-sniffs/WordPress/Sniffs/WP/EnqueuedResourcesSniff.php

**Theme check file covering this rule:**

None.

**Decision needed:**

The sniff looks for scripts and stylesheets included in the templates (via `<script src=[...]>` and `<link rel=[...]>`).

The rule makes an exception for browser workaround scripts.

**Request for decision**:

Given that since WordPress 4.2, `wp_script_add_data()` exists, and browser workaround scripts now can be enqueued (see [TwentySixteen](https://github.com/WordPress/twentysixteen/blob/master/functions.php#L267)), should the rule be changed to encompass _all_ scripts and stylesheets?
#### To do:
- [x] Adjust the rule in the Theme Review handbook.
- [x] Add existing sniff to the ruleset.

**Comment by grappler** [comment]
The requirement will be changed once WP 4.6 is released. https://make.wordpress.org/themes/2016/07/26/meeting-notes-for-2016-july-26/

**Comment by grappler** [comment]
Fixed in 763e8e26ecffd15b7cf1d85eb13556b403181d8d

**Comment by jrfnl** [comment]
Issue should stay open until the handbook has been adjusted. I've added the missing action items for transparency.

**Comment by grappler** [comment]
The handbook has been updated
