### ISSUE TITLE
Check that theme support tags in style.css are being supported.

### ISSUE THREAD

**Issue by khacoder** [WPTRT/WordPress-Coding-Standards#47]
#### Rule type:

ERROR
#### Rule:

ERROR | Verify that tags in style.css that are related to theme support are being supported by the theme.

> Rule as it is found in the handbook.
> Core Functionality and Features
> The theme tags in style.css and description must match the what the theme actually does in respect to functionality and design.
> Ref: https://make.wordpress.org/themes/handbook/review/required/#core-functionality-and-features

custom-header -> if present must have add_theme_support('custom-header')
custom-background -> if present must have add_theme_support('custom-background')
custom-logo -> if present must have add_theme_support('custom-logo')
post-formats -> if present must have add_theme_support('post-formats')
featured-images -> if present must have add_theme_support('post-thumbnails')
featured-image-header -> if present must have add_theme_support('post-thumbnails')
custom-menu -> if present must use register_nav_menu() or wp_nav_menu()
#### Theme check file covering this rule:

There really is no theme check covering this rule.

Note that this is a different sniff then Issue #28.
##### Notes for implementation:
- This sniff will rely on the $theme_data array from the AbstractThemeSniffClass. More specifically the tag list.
- This sniff will rely on the $sniff_helper array from the AbstractThemeSniffClass. More specifically the theme supports list.
- Testing will require that a style.css file is in the same folder as the test file.
#### To do:
- [ ] Create unit tests
- [ ] Create new sniff
- [ ] Adjust existing WPCS / PHPCS sniff and send in PR upstream.
- [ ] Add existing `sniffname` sniff to the ruleset.

**Comment by khacoder** [comment]
I have this sniff ready to go, however it uses the $sniff_helper array from the proposed WordPress_AbstractThemeSniff class.

**Comment by grappler** [comment]
Related PRs #56 #55

**Comment by jrfnl** [comment]
This can't be done properly with PHPCS.
