### ISSUE TITLE
Author and Theme URI's must not be the same

### ISSUE THREAD

**Issue by khacoder** [WPTRT/WordPress-Coding-Standards#48]
[New sniff] Check that Author and Theme URIs in style.css are not the same
#### Rule type:

ERROR
#### Rule:

ERROR | Check in style.css for the Author URI and Theme URI and verify that these are not the same.

> Rule as it is found in the handbook.
> There is no specific rule covering this.
#### Theme check file covering this rule:

https://github.com/Otto42/theme-check/blob/master/checks/uri.php
Note that this theme check also checks that wordpress.org is not part of the URI. This will be moved to a separate sniff.
#### Decision needed:

If we are striving to have rules for sniffs the following rule should be considered.
Selling, credits, and links
- Theme URI and Author URI must not be the same.
##### Notes for implementation:
- This sniff will rely on the WordPress_AbstractThemeSniff Class to get the $sniff_helper array.
- Testing will require that a style.css file is in the same folder as the test file.
#### To do:
- [ ] Decision/Add the rule in the Theme Review handbook to the **_Requirements_** page.
- [ ] Create unit tests
- [ ] Create new sniff
- [ ] Adjust existing WPCS / PHPCS sniff and send in PR upstream.
- [ ] Add existing `sniffname` sniff to the ruleset.

**Comment by khacoder** [comment]
I have this sniff ready to go, however it uses the $sniff_helper array from the proposed WordPress_AbstractThemeSniff class.

**Comment by jrfnl** [comment]
Closing as this will be checked by the new Theme Check plugin already.
