### ISSUE TITLE
[Implement sniff ?] Check for ByteOrderMark

### ISSUE THREAD

**Issue by jrfnl** [WPTRT/WordPress-Coding-Standards#5]
#### Decision needed by Theme Review Board:

There is currently no rule to check for a Unicode Byte Order Mark.

As having a BOM in one of the theme files will often give issues when using those files, it might be a good idea to add this as a rule.

**_Advice_**: Add rule which disallows having a BOM in theme files.
#### To do:
- [x] If agreed this should be a rule - add existing `Generic.Files.ByteOrderMark` sniff to the ruleset.
- [ ] Add the rule in the Theme Review handbook to the Requirements page.

**Comment by grappler** [comment]
Green light to go ahead :
https://make.wordpress.org/themes/2016/07/12/meeting-notes-for-2016-july-12/
