### ISSUE TITLE
Verify that the theme is not auto-generated

### ISSUE THREAD

**Issue by khacoder** [WPTRT/WordPress-Coding-Standards#63]
[New sniff] Verify that the theme is not auto-generated
#### Rule type:

ERROR
#### Rule:

> Generated themes are not allowed in the theme directory.

Ref: I don't think there is a specific requirement that covers this.
#### Theme check file covering this rule:

https://github.com/Otto42/theme-check/blob/master/checks/generate.php
#### To do:
- [ ] Create unit tests
- [ ] Create new sniff
- [ ] Adjust existing WPCS / PHPCS sniff and send in PR upstream.
- [ ] Add existing `sniffname` sniff to the ruleset.

**Comment by grappler** [comment]
The PR has been merged
