### ISSUE TITLE
Use core favicon

### ISSUE THREAD

**Issue by khacoder** [WPTRT/WordPress-Coding-Standards#70]
[New sniff] Check for different kinds of favicons and issue Error if found.

#### Rule type:
Error

#### Rule:

> Use WordPress functionality and features first, if available.

Ref: https://make.wordpress.org/themes/handbook/review/required/#core-functionality-and-features

ERROR | Verify that no favicon / Apple icon / Windows tile / Android whatever they call it is being added from the theme. The current check is in Theme-Check plugin - /checks/favicon.php, but could definitely use some fine-tuning and improvement.

#### Theme check file covering this rule:
https://github.com/Otto42/theme-check/blob/master/checks/favicon.php

#### Decision needed:
Switch from WARNING in themecheck to ERROR in Sniff.

#### To do:
- [ ] Create unit tests
- [ ] Create new sniff
- [ ] Adjust existing WPCS / PHPCS sniff and send in PR upstream.
- [ ] Add existing `sniffname` sniff to the ruleset.

**Comment by khacoder** [comment]
I have this sniff ready to go and will upload after final testing.

**Comment by grappler** [comment]
Changing it to an error makes sense as it was released in WP 4.3 and we have WP 4.6 now which is at least 3 versions ago...
