### ISSUE TITLE
Check for functions that are plugin territory

### ISSUE THREAD

**Issue by khacoder** [WPTRT/WordPress-Coding-Standards#73]
[Implement sniff] Check for functions that are plugin territory and display an error if found.

#### Rule type:
Error

#### Rule:

> The theme options should not be pseudo custom post types and save non-trivial user data. Non-design related functionality is not allowed.

Ref: https://make.wordpress.org/themes/handbook/review/required/#presentation-vs-functionality

ERROR | The following three functions are not allowed (plugin territory): register_post_type(), register_taxonomy(), add_shortcode(). Review this list with the Theme Review board as there might be some more functions which could be added. The sniff could probably just extend the Forbidden Functions sniff - though it should be kept as a separate sniff for clarity.
#### Theme check file covering this rule:
https://github.com/Otto42/theme-check/blob/master/checks/plugin-territory.php

#### To do:
- [x] Create unit tests
- [x] Create new sniff
- [ ] ~~Adjust existing WPCS / PHPCS sniff and send in PR upstream.~~
- [ ] ~~Add existing `sniffname` sniff to the ruleset.~~

**Comment by khacoder** [comment]
I have this sniff ready to go and will upload after final testing.

**Comment by justintadlock** [comment]
More functions:

```
register_taxonomy_for_object_type()
flush_rewrite_rules()
```

There's probably a lot more.  Those two are a couple of the more common ones I've seen.

**Comment by khacoder** [comment]
Sure, keep adding them, the sniff is easy to change.
