### ISSUE TITLE
Not able to put WPCS in Config

### ISSUE THREAD

**Issue by wowthemes** [WPTRT/WordPress-Coding-Standards#75]
I have xampp installed on my system. It already comes with PHPCS and whenever I try to put WPCS into the config, it gives me error that no config file exists. Please guide me what to do :(

**Comment by jrfnl** [comment]
First off: this is not the repository to ask these kind of questions. For questions about WPCS, ask them at [WPCS](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards), for questions about PHPCS, ask them at [PHPCS](https://github.com/squizlabs/PHP_CodeSniffer/).
Please do read the [available](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/blob/develop/README.md) [documentation](https://github.com/squizlabs/PHP_CodeSniffer/wiki) first though as you might not get much of a response if you don't.

All the same, I'll try and help you as an exception.

> whenever I try to put WPCS into **the config**

Into **_which config_** are you trying to add WPCS  and how ? Please provide more detail.

**Comment by wowthemes** [comment]
I am sorry posting at the wrong place.

`phpcs --config-set installed_paths /path/to/wpcs`

When I run this command gettign the following error.
Warning: file_put_contents(C:\php\pear\data/PHP_CodeSniffer/CodeSniffer.conf): failed to open stream: No such file or directory in D:\xampp\php\pear\PHP\CodeSniffer.php on line 1939

I have the phpsc and phpcs.bat file in d:\xampp\php directory

Thanks for your help

**Comment by jrfnl** [comment]
> phpcs --config-set installed_paths /path/to/wpcs

Did you adjust the `/path/to/wpcs` part to the folder in which you have WPCS installed ? If not, that is part of your problem.

Is the `phpcs` command available globally, i.e. from every directory on your computer or not ? If not, make sure you actually run the command from a directory where it is available.

**Comment by wowthemes** [comment]
Yes, I have adjust the path to where wpcs is placed. Also I have access to phpcs globally. It is added into Environment Variables.

**Comment by jrfnl** [comment]
Ok - next, as it says in the error message, check in the `C:\php\pear\data/PHP_CodeSniffer/` directory whether you have a file there called `CodeSniffer.conf`. You probably don't. 
So, you can either create an empty file called `CodeSniffer.conf` or copy the `CodeSniffer.conf.dist` file which most likely is there and rename the copy to `CodeSniffer.conf`.

**Comment by wowthemes** [comment]
Yes, now it works but whenever I run the check command 
`phpcs -i`
It says 

`The installed coding standards are MySource, PEAR, PHPCS, Squiz and Zend`

Not WordPress :(

**Comment by jrfnl** [comment]
Ok, can you open up the `CodeSniffer.conf` file and copy & paste what it says in there here for me to have a look ?

**Comment by wowthemes** [comment]
Here is what I can see 

`<?php
 $phpCodeSnifferConfig = array (
  'default_standard' => 'PSR2',
  'report_format' => 'summary',
  'show_warnings' => '0',
  'show_progress' => '1',
  'report_width' => '120',
  'installed_paths' => 'd:/xampp/htdocs/phpcs/wpcs',
)
?>`

**Comment by jrfnl** [comment]
Ok, you can remove everything in the array but the `installed_paths` bit (just to make sure none of the other settings is interfering), so the file would look like:

```php
<?php
 $phpCodeSnifferConfig = array (
  'installed_paths' => 'd:/xampp/htdocs/phpcs/wpcs',
);
?>
```

And can you confirm that `d:/xampp/htdocs/phpcs/wpcs` is the directory in which WPCS is installed ?
and that it is the root directory of the WPCS project, i.e. the directory should have the following sub-directories (and possibly more if it's a fork/copy of this fork, not of the WPCS main project):
```
d:/xampp/htdocs/phpcs/wpcs
	- WordPress
	- WordPress-Core
	- WordPress-Docs
	- WordPress-Extra
	- WordPress-VIP
```

**Comment by wowthemes** [comment]
Yes, its confirmed, the path correct and I have the following directories
`d:/xampp/htdocs/phpcs/wpcs
    - WordPress
    - WordPress-Core
    - WordPress-Docs
    - WordPress-Extra
    - WordPress-VIP`

But still no luck :(

It seems that it is reading config from somewhere else. Please see the attached CodeSniffer file.
[CodeSniffer.zip](https://github.com/WPTRT/WordPress-Coding-Standards/files/436826/CodeSniffer.zip)

**Comment by jrfnl** [comment]
> It seems that it is reading config from somewhere else. 

That must be the case. However the attached file does not help with that.

Questions which should help determine from where are:
* Do you have PHPCS installed somewhere else as well ?
* Is the `CodeSniffer.conf` file placed in the `C:\php\pear\data/PHP_CodeSniffer/` directory or did you put it elsewhere ?
* Where does the `phpcs.bat` file point to for finding PHPCS ?
* What is the value of your `PHP_PEAR_DATA` environment variable ? (Though I don't suspect that is the problem)
* What is the value of your `Path` system variable ?

**Comment by wowthemes** [comment]
For Environment Variable paths please see the attachment 
![untitled](https://cloud.githubusercontent.com/assets/16266732/17967939/979905ac-6ae3-11e6-8e29-d0c42abfab19.png)

- 
- Path to CodeSniffer.conf file is d:\xampp\php\pear\PHP\CodeSniffer.conf and same for CodeSniffer.php
- Path to phpsc is d:\xampp\php\phpcs
- Path to phpsc.bat is d:\xampp\php\phpsc.bat

Thanks for your help

**Comment by jrfnl** [comment]
Ok, just looking at your screenshot, I can already see that you have a second copy of PHPCS installed in `D:\xampp\htdocs\phpcs\`, so more than likely the phpcs.bat file in that directory is being used instead of the one in the PEAR directory, which also means that PHPCS will be looking for the `.conf` file in `D:\xampp\htdocs\phpcs\` not in the PEAR data directory.

Secondly, you say your `CodeSniffer.conf` is located at `file is d:\xampp\php\pear\PHP\CodeSniffer.conf ` not in the `C:\php\pear\data/PHP_CodeSniffer/` directory.

Both are wrong and cause your problems

The simple solution is to copy the `d:\xampp\php\pear\PHP\CodeSniffer.conf` file to the correct location for both installs:
* `C:\php\pear\data/PHP_CodeSniffer/CodeSniffer.conf` for the PEAR install.
* `D:\xampp\htdocs\phpcs\CodeSniffer.conf` for the second install.

After that, remove the file from the original (wrong) location `d:\xampp\php\pear\PHP\CodeSniffer.conf`

Then, keep your fingers crossed and run `phpcs -i` again :sunglasses:

**Comment by wowthemes** [comment]
Actually `C:\php\pear\data/PHP_CodeSniffer/` path is totally not exist. CodeSniffer.php first looks for config in the same directory where `CodeSniffer.php` is itself  and it is placed in `d:\xampp\php\pear\PHP\CodeSniffer.php` 

Is it possible that I search for something specific in the whole directory to find out from where it is reading the configurations.

**Comment by wowthemes** [comment]
Is there a way I disable phpcs comes with Xampp and install it as per phpcs and wpcs way?

**Comment by jrfnl** [comment]
> Actually C:\php\pear\data/PHP_CodeSniffer/ path is totally not exist.

So create it. That will prevent your file from being overwritten when you update the PEAR install of PHPCS.

> Is there a way I disable phpcs comes with Xampp and install it as per phpcs and wpcs way?

Yes, uninstall it from your PEAR install. Install composer and run it to install PHPCS and WPCS.

**Comment by wowthemes** [comment]
I did the first step but no luck. 

I try to uninstall phpcs and then re-install it.

Thanks a lot for your help :+1:

**Comment by wowthemes** [comment]
I have disabled the pear phpcs installation and re-install PHPCS to a new location/directory by following the instructions at [https://github.com/squizlabs/PHP_CodeSniffer](https://github.com/squizlabs/PHP_CodeSniffer) and this time successful. Everything now works fine. Thanks @jrfnl

**Comment by jrfnl** [comment]
Glad to hear it. Enjoy!
