### ISSUE TITLE
[Existing Sniff] Disallow Error Silencing

### ISSUE THREAD

**Issue by grappler** [WPTRT/WordPress-Coding-Standards#83]
#### Rule type:
Error - (No) Error Control Operator @

#### Rule:

> No PHP or JS errors.

PHP errors should not be silenced

Ref: https://make.wordpress.org/themes/handbook/review/required/#code

#### To do:
- [x] Document the check in the Theme Review handbook to the **_Requirements_** page.
- [x] Add existing `<rule ref="Generic.PHP.NoSilencedErrors" />` sniff to the ruleset.

**Comment by ernilambar** [comment]
@grappler This is currently WARNING. Is not this supposed to be ERROR?

**Comment by grappler** [comment]
@ernilambar Yes, it should be a error.

**Comment by jrfnl** [comment]
PR #99 should solve that ;-)
