### ISSUE TITLE
[Implement sniff] WordPress must be spelled correctly

### ISSUE THREAD

**Issue by grappler** [WPTRT/WordPress-Coding-Standards#88]
#### Rule:

> Spell “WordPress” correctly in all public facing text: all one word, with both an uppercase W and P.

Ref: Link to the Theme Review handbook page & subsection where the rule can be found, i.e. https://make.wordpress.org/themes/handbook/review/required/#naming

We do not need to make this just public facing as it is automated. The only exception that I can think of is when it is being used in a function then it can be all lower case.

~~#### To do:~~
~~- [ ] Create unit tests~~
~~- [ ] Create new sniff~~

**Comment by jrfnl** [comment]
A PR for the actual sniff has been pulled upstream https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/pull/909.

What would now be needed for TRTCS:
- [ ] Merge back WPCS `develop` into "our" branch after the above PR has been merged
- [ ] Add the new sniff to the TRT ruleset
