### ISSUE TITLE
[New sniff?] Check for non-printable characters

### ISSUE THREAD

**Issue by jrfnl** [WPTRT/WordPress-Coding-Standards#94]
#### Rule type:
Warning

#### Rule:

> Check for non-printable characters `[\x00-\x08\x0B-\x0C\x0E-\x1F\x80-\xFF]`

Ref: https://make.wordpress.org/themes/handbook/review/required/theme-check-plugin/#info

#### Theme check file covering this rule:
https://github.com/WordPress/theme-check/blob/master/checks/nonprintable.php

##### Notes for implementation:
* Quite possibly there will be an existing sniff somewhere we could re-use for this.

#### To do:
- [ ] Maybe clarify the rule in the Theme Review handbook
- [ ] Research if there is an existing sniff we could reuse, if so, add that sniff to the ruleset
- [ ] Otherwise: Create unit tests
- [ ] Otherwise: Create new sniff

**Comment by grappler** [comment]
For this sniff we can most likely use the token `T_BAD_CHARACTER`

**Comment by selul** [comment]
i would like to try this.

**Comment by jrfnl** [comment]
From: https://github.com/WPTRT/WordPress-Coding-Standards/pull/103#issuecomment-274278772

> I spoke to Otto and the reason this was added in the Theme Check was to check for Byte Order Mark. Explanation. This is now being checked with Generic.Files.ByteOrderMark
> 
> The check was made a bit looser to try to catch other issues too.
> 
> I did a bit of research, non printable characters are things like line breaks. In order for this sniff to work we would need to think of places where it does not make sense to have non printable characters. I am not sure how many places there are.
> 
> More of the ASCII codes can be found in the links 1-31 and 127-159 are the invisible characters.
> http://ascii.cl/htmlcodes.htm
> http://www.ascii-code.com/

It basically needs to become clear whether just checking for the BOM is enough, or checking for more non-printables is needed.

If the latter, PR #103 contains the basic principle of a sniff for that, but should in that case probably be pulled upstream, either in WPCS or - even better - in PHPCS itself.
